// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/** Dotenv / tooling sometimes leaves wrapping quotes in values — strip them. */
function normalizeEnvValue(v: unknown): string {
  if (typeof v !== "string") return "";
  let s = v.trim();
  if (s.length >= 2) {
    const q = s[0];
    if ((q === '"' || q === "'") && s[s.length - 1] === q) {
      s = s.slice(1, -1).trim();
    }
  }
  return s;
}

function readEnv() {
  const url = normalizeEnvValue(
    import.meta.env.VITE_SUPABASE_URL ?? process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL,
  );
  const key = normalizeEnvValue(
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
      import.meta.env.VITE_SUPABASE_ANON_KEY ??
      process.env.SUPABASE_PUBLISHABLE_KEY ??
      process.env.SUPABASE_ANON_KEY ??
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
      process.env.VITE_SUPABASE_ANON_KEY,
  );
  return { url, key };
}

export function isSupabaseConfigured(): boolean {
  const { url, key } = readEnv();
  return Boolean(url && key);
}

/**
 * `ref` claim from the publishable/anon JWT — same segment as `xxxx` in `https://xxxx.supabase.co`.
 * Use for dashboard deep links so they match the key actually in use (env `VITE_SUPABASE_PROJECT_ID` can be stale).
 */
export function getSupabaseProjectRefFromKey(): string | null {
  const { key } = readEnv();
  if (!key) return null;
  const parts = key.split(".");
  if (parts.length < 2) return null;
  try {
    let b64 = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    const pad = b64.length % 4;
    if (pad) b64 += "=".repeat(4 - pad);
    const payload = JSON.parse(atob(b64)) as { ref?: unknown };
    return typeof payload.ref === "string" ? payload.ref : null;
  } catch {
    return null;
  }
}

let _client: SupabaseClient<Database> | undefined;

/**
 * Browser Supabase client. Returns `null` only while URL/key are missing.
 * Does **not** cache a failed init: first SSR pass without env must not lock the client to null forever.
 */
export function getSupabase(): SupabaseClient<Database> | null {
  const { url, key } = readEnv();
  if (!url || !key) {
    return null;
  }
  if (!_client) {
    _client = createClient<Database>(url, key, {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  }
  return _client;
}
